# ruff: noqa: UP006, UP035, UP045, B905, E501  (vendored PolarMACE.forward upstream style)
"""SolvatedPolarMACE: PolarMACE with a self-consistent continuum reaction field.

Base ``PolarMACE`` re-polarises the solute density over ``num_recursion_steps`` learned update
steps, driven by the solute's own Coulomb field + any external field. This subclass injects the
**solvent reaction field** into that loop so the solute re-polarises to the medium -- the
mechanism the one-shot ``LocalSplitCharges`` reaction field cannot provide (there the field only
adds a post-hoc energy and never re-polarises the charges).

The reaction potential (l=0, couples to atomic charge) and reaction field (l=1, couples to the
atomic dipole) come from a swappable :class:`ReactionFieldProvider` -- generalized-Born (monopole
baseline) or generalized-Kirkwood (charge + dipole; the polarizable tier). They are projected into
the field-feature basis with the per-atom ``GTOInternalFieldtoFeaturesBlock`` and added exactly
where the external field enters the loop. The solvation free energy is added once, from the
converged density.

The ``forward`` below is a VENDORED COPY of ``mace.modules.extensions.PolarMACE.forward`` (pinned
to the installed mace-torch, no upstream mid-loop hook exists) with three clearly-fenced
insertions: the reaction-field inputs, the in-loop injection, and the post-loop energy. It is
generated by ``scratchpad/build_solvated_polar_mace.py`` from the installed source so the copy
stays byte-exact; regenerate it if the mace-torch pin changes.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional  # noqa: F401  (used by the vendored forward)

import torch
from graph_longrange.gto_utils import GTOInternalFieldtoFeaturesBlock
from graph_longrange.kspace import compute_k_vectors_flat  # noqa: F401
from mace.modules.extensions import (  # noqa: F401
    GRAPH_LONGRANGE_AVAILABLE,
    PolarMACE,
    _permute_to_e3nn_convention,
)
from mace.modules.utils import (  # noqa: F401
    compute_total_charge_dipole_permuted,
    get_atomic_virials_stresses,
    get_outputs,
    prepare_graph,
)
from mace.tools.scatter import scatter_mean, scatter_sum  # noqa: F401

from .reaction_field.ddcosmo_provider import DdcosmoReactionFieldProvider
from .reaction_field.generalized_kirkwood import (
    GENERALIZED_KIRKWOOD_GAUSSIAN_CONSTANT,
    GeneralizedKirkwoodReactionField,
)
from .reaction_field.reaction_potential import GeneralizedBornReactionField

REACTION_FIELD_SCHEMES = ("generalized_born", "generalized_kirkwood", "ddcosmo")


class SolvatedPolarMACE(PolarMACE):
    def __init__(
        self,
        *,
        reaction_field_scheme: str = "generalized_kirkwood",
        reaction_field_smearing_width: Optional[float] = None,
        generalized_kirkwood_gaussian_constant: float = (
            GENERALIZED_KIRKWOOD_GAUSSIAN_CONSTANT
        ),
        ddcosmo_lebedev_order: int = 29,
        ddcosmo_max_spherical_harmonic_order: int = 6,
        **kwargs: Any,
    ) -> None:
        num_interactions = kwargs.get("num_interactions")
        if num_interactions is not None and int(num_interactions) < 2:
            raise ValueError(
                "SolvatedPolarMACE (PolarMACE base) requires num_interactions >= 2; the "
                "single-layer readout/source structure is not supported (it fails with an "
                f"opaque reshape error in the forward). Got num_interactions={num_interactions}."
            )
        super().__init__(**kwargs)
        if self.field_feature_max_l < 1:
            raise ValueError(
                "SolvatedPolarMACE needs field_feature_max_l >= 1 so the l=1 field channel "
                "exists to carry the reaction field onto the atomic dipoles; got "
                f"field_feature_max_l={self.field_feature_max_l}."
            )
        smearing_width = (
            reaction_field_smearing_width
            if reaction_field_smearing_width is not None
            else self.atomic_multipoles_smearing_width
        )
        if reaction_field_scheme == "generalized_born":
            self.reaction_field_provider = GeneralizedBornReactionField(
                smearing_width=smearing_width
            )
        elif reaction_field_scheme == "generalized_kirkwood":
            self.reaction_field_provider = GeneralizedKirkwoodReactionField(
                smearing_width=smearing_width,
                gaussian_constant=generalized_kirkwood_gaussian_constant,
            )
        elif reaction_field_scheme == "ddcosmo":
            self.reaction_field_provider = DdcosmoReactionFieldProvider(
                smearing_width=smearing_width,
                lebedev_order=ddcosmo_lebedev_order,
                max_spherical_harmonic_order=ddcosmo_max_spherical_harmonic_order,
            )
        else:
            raise ValueError(
                f"Unknown reaction_field_scheme {reaction_field_scheme!r}; "
                f"expected one of {REACTION_FIELD_SCHEMES}."
            )
        self.reaction_field_scheme = reaction_field_scheme
        self.reaction_field_projection = GTOInternalFieldtoFeaturesBlock(
            self.field_feature_max_l, self.field_feature_widths, "receiver"
        )
        # e3nn l=1 order is (y, z, x); Cartesian (x, y, z) = e3nn[[2, 0, 1]] (CS phase).
        self.register_buffer("cartesian_permutation", torch.tensor([2, 0, 1]))

    def _physical_multipoles(
        self, density_coefficients_mul_ir: torch.Tensor, positions: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Physical per-atom monopole charge and Cartesian atomic dipole from the density."""
        monopole = density_coefficients_mul_ir[:, 0]
        if density_coefficients_mul_ir.shape[1] >= 4:
            atomic_dipole = density_coefficients_mul_ir[:, 1:4].index_select(
                1, self.cartesian_permutation
            )
        else:
            atomic_dipole = torch.zeros(
                (density_coefficients_mul_ir.shape[0], 3),
                dtype=positions.dtype,
                device=positions.device,
            )
        return monopole, atomic_dipole

    def _reaction_node_features(
        self,
        spin_charge_density: torch.Tensor,
        positions: torch.Tensor,
        atomic_numbers: torch.Tensor,
        batch: torch.Tensor,
        dielectric_constant: torch.Tensor,
    ) -> torch.Tensor:
        """Reaction (phi, E) from the current density, projected to field features [n_node, d]."""
        current = spin_charge_density.sum(dim=1)
        if self._charges_to_mul_ir is not None:
            current = self._charges_to_mul_ir(current)
        monopole, atomic_dipole = self._physical_multipoles(current, positions)
        reaction_potential, reaction_field, _ = self.reaction_field_provider(
            monopole, atomic_dipole, positions, atomic_numbers, batch, dielectric_constant
        )
        node_fields = torch.stack(
            [
                reaction_potential,
                reaction_field[:, 0],
                reaction_field[:, 1],
                reaction_field[:, 2],
            ],
            dim=-1,
        )
        return self.reaction_field_projection(batch, positions, node_fields)

    def _reaction_solvation_energy(
        self,
        density_coefficients_mul_ir: torch.Tensor,
        positions: torch.Tensor,
        atomic_numbers: torch.Tensor,
        batch: torch.Tensor,
        dielectric_constant: torch.Tensor,
    ) -> torch.Tensor:
        """Reaction free energy [n_graphs] from the converged density."""
        monopole, atomic_dipole = self._physical_multipoles(
            density_coefficients_mul_ir, positions
        )
        _, _, energy = self.reaction_field_provider(
            monopole, atomic_dipole, positions, atomic_numbers, batch, dielectric_constant
        )
        return energy

    def forward(
        self,
        data: Dict[str, torch.Tensor],
        training: bool = False,
        compute_force: bool = True,
        compute_virials: bool = False,
        compute_stress: bool = False,
        compute_displacement: bool = False,
        compute_hessian: bool = False,
        compute_edge_forces: bool = False,
        compute_atomic_stresses: bool = False,
        lammps_mliap: bool = False,
        use_pbc_evaluator: bool = False,
        fermi_level: Optional[torch.Tensor] = None,
        external_field: Optional[torch.Tensor] = None,
    ) -> Dict[str, Optional[torch.Tensor]]:
        if not GRAPH_LONGRANGE_AVAILABLE:
            raise ImportError(
                "Cannot import 'graph_longrange'. Please install graph_electrostatics "
                "from https://github.com/WillBaldwin0/graph_electrostatics."
            )
        ctx = prepare_graph(
            data,
            compute_virials=compute_virials,
            compute_stress=compute_stress,
            compute_displacement=compute_displacement,
            lammps_mliap=lammps_mliap,
        )

        is_lammps = ctx.is_lammps
        num_atoms_arange = ctx.num_atoms_arange
        num_graphs = ctx.num_graphs
        displacement = ctx.displacement
        positions = ctx.positions
        vectors = ctx.vectors
        lengths = ctx.lengths
        cell = ctx.cell
        node_heads = ctx.node_heads
        interaction_kwargs = ctx.interaction_kwargs
        lammps_natoms = interaction_kwargs.lammps_natoms
        lammps_class = interaction_kwargs.lammps_class

        if fermi_level is None:
            fermi_level = data["fermi_level"]
        if external_field is None:
            external_field = data["external_field"]
        external_potential = torch.hstack(
            (torch.zeros_like(fermi_level).unsqueeze(-1), external_field)
        )
        # --- BEGIN reaction-field (implicit solvation) inputs ---
        reaction_atomic_numbers = self.atomic_numbers[
            torch.argmax(data["node_attrs"], dim=1)
        ]
        if "dielectric_constant" in data:
            reaction_dielectric = data["dielectric_constant"].view(-1)
        else:
            reaction_dielectric = torch.ones(
                num_graphs, dtype=positions.dtype, device=positions.device
            )
        # --- END reaction-field inputs ---
        charges_to_mul_ir = getattr(self, "_charges_to_mul_ir", None)

        node_e0 = self.atomic_energies_fn(data["node_attrs"])[
            num_atoms_arange, node_heads
        ]
        e0 = scatter_sum(
            src=node_e0, index=data["batch"], dim=0, dim_size=num_graphs
        ).to(vectors.dtype)

        node_feats = self.node_embedding(data["node_attrs"])
        edge_attrs = self.spherical_harmonics(_permute_to_e3nn_convention(vectors))
        edge_feats, cutoff = self.radial_embedding(
            lengths, data["node_attrs"], data["edge_index"], self.atomic_numbers
        )
        if hasattr(self, "pair_repulsion"):
            pair_node_energy = self.pair_repulsion_fn(
                lengths, data["node_attrs"], data["edge_index"], self.atomic_numbers
            )
            if is_lammps:
                pair_node_energy = pair_node_energy[: lammps_natoms[0]]
        else:
            pair_node_energy = torch.zeros_like(node_e0)

        node_es_list: List[torch.Tensor] = []
        node_feats_list: List[torch.Tensor] = []
        spin_charge_density = torch.zeros(
            (data["batch"].size(-1), self.charges_irreps.dim),
            device=data["batch"].device,
            dtype=vectors.dtype,
        )

        for i, (interaction, product, lr_src) in enumerate(
            zip(self.interactions, self.products, self.lr_source_maps)
        ):
            node_attrs_slice = data["node_attrs"]
            if is_lammps and i > 0:
                node_attrs_slice = node_attrs_slice[: lammps_natoms[0]]
            node_feats, sc = interaction(
                node_attrs=node_attrs_slice,
                node_feats=node_feats,
                edge_attrs=edge_attrs,
                edge_feats=edge_feats,
                edge_index=data["edge_index"],
                cutoff=cutoff,
                first_layer=(i == 0),
                lammps_class=lammps_class,
                lammps_natoms=lammps_natoms,
            )
            if is_lammps and i == 0:
                node_attrs_slice = node_attrs_slice[: lammps_natoms[0]]
            node_feats = product(
                node_feats=node_feats, sc=sc, node_attrs=node_attrs_slice
            )
            node_feats_list.append(node_feats)

            feat_idx = -1 if len(self.readouts) == 1 else min(i, len(self.readouts) - 1)
            node_es = self.readouts[feat_idx](node_feats, node_heads)[
                num_atoms_arange, node_heads
            ]
            node_es_list.append(node_es)

            spin_charge_sources = lr_src(node_feats).squeeze(-2)
            spin_charge_density = spin_charge_density + spin_charge_sources

        node_feats_out = torch.cat(node_feats_list, dim=-1)
        node_inter_es = torch.sum(torch.stack(node_es_list, dim=0), dim=0)
        node_inter_es = self.scale_shift(node_inter_es, node_heads)
        inter_e = scatter_sum(node_inter_es, data["batch"], dim=-1, dim_size=num_graphs)

        # Build k-grid
        (
            k_vectors,
            kv_norms_squared,
            k_vectors_batch,
            k_vectors_0mask,
        ) = compute_k_vectors_flat(
            self.kspace_cutoff, cell.view(-1, 3, 3), data["rcell"].view(-1, 3, 3)
        )

        field_feature_cache = self.electric_potential_descriptor.precompute_geometry(
            k_vectors=k_vectors,
            k_norm2=kv_norms_squared,
            k_vector_batch=k_vectors_batch,
            k0_mask=k_vectors_0mask,
            node_positions=positions,
            batch=data["batch"],
            volume=data["volume"],
            pbc=data["pbc"].view(-1, 3),
            force_pbc_evaluator=use_pbc_evaluator,
        )

        # SCF fixed point
        features_mixed = self.layer_feature_mixer(torch.stack(node_feats_list, dim=0))
        spin_charge_density = spin_charge_density.view(
            spin_charge_density.shape[0], 2, -1
        )
        fukui_input = node_feats
        fukui_to_mul_ir = getattr(self, "_fukui_to_mul_ir", None)
        if fukui_to_mul_ir is not None:
            fukui_input = fukui_to_mul_ir(fukui_input)
        fukui_sources = self.fukui_source_map(fukui_input)
        fukui_norm = scatter_sum(
            src=fukui_sources.double(),
            index=data["batch"],
            dim=0,
            dim_size=num_graphs,
        )[data["batch"]].to(vectors.dtype)
        fukui_norm = torch.where(
            fukui_norm == 0, torch.ones_like(fukui_norm), fukui_norm
        )
        fukui_sources = fukui_sources / fukui_norm
        Q_p_S = (data["total_charge"] + (data["total_spin"] - 1))[data["batch"]]
        Q_m_S = (data["total_charge"] - (data["total_spin"] - 1))[data["batch"]]
        pred_total_charges_0 = scatter_sum(
            src=spin_charge_density[:, :, 0].double(),
            index=data["batch"],
            dim=0,
            dim_size=num_graphs,
        )[data["batch"]].to(vectors.dtype)
        spin_charge_density = spin_charge_density.clone()
        spin_charge_density[:, 0, 0] = spin_charge_density[:, 0, 0] + fukui_sources[
            :, 0
        ] * ((Q_p_S / 2) - pred_total_charges_0[:, 0])
        spin_charge_density[:, 1, 0] = spin_charge_density[:, 1, 0] + fukui_sources[
            :, 1
        ] * ((Q_m_S / 2) - pred_total_charges_0[:, 1])
        # print("spin_charge_density", spin_charge_density)

        potential_features = torch.zeros(
            (data["batch"].size(-1), self.potential_irreps.dim),
            device=data["batch"].device,
            dtype=vectors.dtype,
        )
        field_independent_spin_charge_density = spin_charge_density.clone()
        esps: Optional[torch.Tensor] = None

        for i in range(self.num_recursion_steps):
            source_feats_alpha = spin_charge_density[:, 0, :].clone()
            source_feats_beta = spin_charge_density[:, 1, :].clone()
            if charges_to_mul_ir is not None:
                source_feats_alpha = charges_to_mul_ir(source_feats_alpha)
                source_feats_beta = charges_to_mul_ir(source_feats_beta)
            field_feats_alpha = self.electric_potential_descriptor.forward_dynamic(
                cache=field_feature_cache,
                source_feats=source_feats_alpha.unsqueeze(-2),
                pbc=data["pbc"].view(-1, 3),
            )
            field_feats_beta = self.electric_potential_descriptor.forward_dynamic(
                cache=field_feature_cache,
                source_feats=source_feats_beta.unsqueeze(-2),
                pbc=data["pbc"].view(-1, 3),
            )
            field_from_mul_ir = getattr(self, "_field_from_mul_ir", None)
            if field_from_mul_ir is not None:
                field_feats_alpha = field_from_mul_ir(field_feats_alpha)
                field_feats_beta = field_from_mul_ir(field_feats_beta)
            esps = None

            # Add external field contribution and subtract barycenter for gauge invariance
            barycenter = scatter_mean(
                src=positions.double(),
                index=data["batch"],
                dim=0,
                dim_size=num_graphs,
            ).to(positions.dtype)
            half_external_field = 0.5 * self.external_field_contribution(
                data["batch"],
                positions - barycenter[data["batch"], :],
                external_potential,
            )
            # --- BEGIN reaction-field injection: the solvent reaction potential (l=0) and
            #     field (l=1) from the CURRENT density, so the charge update re-polarises to the
            #     medium. Spin-independent, added exactly where the external field enters. ---
            reaction_node_features = self._reaction_node_features(
                spin_charge_density,
                positions,
                reaction_atomic_numbers,
                data["batch"],
                reaction_dielectric,
            )
            # --- END reaction-field injection ---
            field_feats_alpha = (
                field_feats_alpha + half_external_field + reaction_node_features
            ) / self.field_feature_norms
            field_feats_beta = (
                field_feats_beta + half_external_field + reaction_node_features
            ) / self.field_feature_norms

            potential_features = torch.cat(
                (field_feats_alpha, field_feats_beta), dim=-1
            )
            charge_sources_out = self.field_dependent_charges_maps[i](
                node_attrs=data["node_attrs"],
                node_feats=features_mixed,
                edge_attrs=edge_attrs[:, : self.from_ell_max_field_update],
                edge_feats=edge_feats,
                edge_index=data["edge_index"],
                potential_features=potential_features,
                local_charges=spin_charge_density.view(
                    spin_charge_density.shape[0], -1
                ),
            )

            current_fukui_sources = charge_sources_out[:, -2:]
            charge_sources = charge_sources_out[:, :-2]
            # print("charge_sources", charge_sources)
            # print("current_fukui_sources", current_fukui_sources)
            spin_charge_density_sources = charge_sources.view(
                spin_charge_density.shape[0], 2, -1
            )
            spin_charge_density = spin_charge_density + spin_charge_density_sources

            fukui_norm2 = scatter_sum(
                src=current_fukui_sources.double(),
                index=data["batch"],
                dim=0,
                dim_size=num_graphs,
            )[data["batch"]].to(vectors.dtype)
            fukui_norm2 = torch.where(
                fukui_norm2 == 0, torch.ones_like(fukui_norm2), fukui_norm2
            )
            current_fukui_sources = current_fukui_sources / fukui_norm2
            pred_total_charges = scatter_sum(
                src=spin_charge_density[:, :, 0].double(),
                index=data["batch"],
                dim=0,
                dim_size=num_graphs,
            )[data["batch"]].to(vectors.dtype)
            spin_charge_density = spin_charge_density.clone()
            spin_charge_density[:, 0, 0] = spin_charge_density[
                :, 0, 0
            ] + current_fukui_sources[:, 0] * ((Q_p_S / 2) - pred_total_charges[:, 0])
            spin_charge_density[:, 1, 0] = spin_charge_density[
                :, 1, 0
            ] + current_fukui_sources[:, 1] * ((Q_m_S / 2) - pred_total_charges[:, 1])

        total_energy = e0 + inter_e
        local_q_e = self.local_electron_energy(
            node_attrs=data["node_attrs"],
            node_feats=node_feats,
            edge_attrs=edge_attrs[:, : self.from_ell_max_field_update],
            edge_feats=edge_feats,
            edge_index=data["edge_index"],
            field_feats=potential_features,
            charges_0=field_independent_spin_charge_density.view(
                field_independent_spin_charge_density.shape[0], -1
            ),
            charges_induced=spin_charge_density.view(spin_charge_density.shape[0], -1),
        )
        le_total = scatter_sum(
            src=local_q_e, index=data["batch"], dim=-1, dim_size=num_graphs
        )
        if getattr(self, "add_local_electron_energy", False):
            total_energy = total_energy + le_total
        else:
            le_total = torch.zeros_like(le_total)

        charge_density = spin_charge_density.sum(dim=1)
        spin_density = spin_charge_density[:, 0, :] - spin_charge_density[:, 1, :]
        charge_density_mul_ir = (
            charges_to_mul_ir(charge_density)
            if charges_to_mul_ir is not None
            else charge_density
        )
        spin_density_mul_ir = (
            charges_to_mul_ir(spin_density)
            if charges_to_mul_ir is not None
            else spin_density
        )
        spin_charge_density_mul_ir = (
            torch.stack(
                [
                    charges_to_mul_ir(spin_charge_density[:, 0, :]),
                    charges_to_mul_ir(spin_charge_density[:, 1, :]),
                ],
                dim=1,
            )
            if charges_to_mul_ir is not None
            else spin_charge_density
        )
        total_charge, total_dipole = compute_total_charge_dipole_permuted(
            charge_density_mul_ir, positions, data["batch"], num_graphs
        )
        electro_energy = self.coulomb_energy(
            k_vectors=k_vectors,
            k_norm2=kv_norms_squared,
            k_vector_batch=k_vectors_batch,
            k0_mask=k_vectors_0mask,
            source_feats=charge_density_mul_ir,
            node_positions=positions,
            batch=data["batch"],
            volume=data["volume"],
            pbc=data["pbc"].view(-1, 3),
            force_pbc_evaluator=use_pbc_evaluator,
        )
        total_energy = (
            total_energy
            + electro_energy
            + torch.sum(external_potential[:, 1:] * total_dipole, dim=-1)
        )
        # --- BEGIN reaction-field (implicit solvation) energy: added ONCE from the
        #     converged density. The in-loop injection drives re-polarisation but adds no energy;
        #     the free energy is 0.5 * sum_i (q_i phi_i + mu_i . E_i). ---
        reaction_solvation_energy = self._reaction_solvation_energy(
            charge_density_mul_ir,
            positions,
            reaction_atomic_numbers,
            data["batch"],
            reaction_dielectric,
        )
        total_energy = total_energy + reaction_solvation_energy
        # --- END reaction-field energy ---

        forces, virials, stress, hessian, edge_forces = get_outputs(
            energy=total_energy,
            positions=positions,
            displacement=displacement,
            vectors=vectors,
            cell=cell,
            training=training,
            compute_force=compute_force,
            compute_virials=compute_virials,
            compute_stress=compute_stress,
            compute_hessian=compute_hessian,
            compute_edge_forces=compute_edge_forces or compute_atomic_stresses,
        )

        atomic_virials: Optional[torch.Tensor] = None
        atomic_stresses: Optional[torch.Tensor] = None
        if compute_atomic_stresses and edge_forces is not None:
            from mace.modules.utils import get_atomic_virials_stresses as _gav

            atomic_virials, atomic_stresses = _gav(
                edge_forces=edge_forces,
                edge_index=data["edge_index"],
                vectors=vectors,
                num_atoms=positions.shape[0],
                batch=data["batch"],
                cell=cell,
            )

        return {
            "energy": total_energy,
            "node_energy": node_e0.clone().double() + node_inter_es.clone().double(),
            "interaction_energy": inter_e,
            "forces": forces,
            "edge_forces": edge_forces,
            "virials": virials,
            "stress": stress,
            "atomic_virials": atomic_virials,
            "atomic_stresses": atomic_stresses,
            "hessian": hessian,
            "displacement": displacement,
            "node_feats": node_feats_out,
            "density_coefficients": charge_density_mul_ir,
            "spin_density": spin_density_mul_ir,
            "charges_history": torch.stack(
                [spin_charge_density_mul_ir.clone().detach()], dim=-1
            ),
            "fermi_level": external_potential[:, 0],
            "external_field": external_potential[:, 1:],
            "charges": charge_density_mul_ir[:, 0],
            "spins": spin_density_mul_ir[:, 0],
            "dipole": total_dipole,
            "total_charge": total_charge,
            "electrostatic_energy": electro_energy,
            "electron_energy": le_total,
            "electrostatic_potentials": esps,
            "spin_charge_density": spin_charge_density_mul_ir,
        }

